# Form implementation generated from reading ui file 'qt_design.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindow_class(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 744)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Get_Coord = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Get_Coord.setGeometry(QtCore.QRect(30, 110, 241, 31))
        self.Get_Coord.setObjectName("Get_Coord")
        self.Get_Ma_bt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Get_Ma_bt.setGeometry(QtCore.QRect(30, 160, 241, 51))
        self.Get_Ma_bt.setObjectName("Get_Ma_bt")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 231, 41))
        self.label.setObjectName("label")
        self.Map = QtWidgets.QLabel(parent=self.centralwidget)
        self.Map.setGeometry(QtCore.QRect(310, 90, 571, 541))
        self.Map.setText("")
        self.Map.setObjectName("Map")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Get_Ma_bt.setText(_translate("MainWindow", "Отобразить карту"))
        self.label.setText(_translate("MainWindow", "Введите координаты"))
