# Form implementation generated from reading ui file 'qt_design_2.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindow_class(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 744)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_field_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.map_field_lbl.setGeometry(QtCore.QRect(350, 30, 541, 631))
        self.map_field_lbl.setText("")
        self.map_field_lbl.setObjectName("map_field_lbl")
        self.pls_coordinates_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.pls_coordinates_lbl.setGeometry(QtCore.QRect(10, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pls_coordinates_lbl.setFont(font)
        self.pls_coordinates_lbl.setObjectName("pls_coordinates_lbl")
        self.get_coord_led = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.get_coord_led.setGeometry(QtCore.QRect(10, 50, 321, 31))
        self.get_coord_led.setObjectName("get_coord_led")
        self.display_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.display_btn.setGeometry(QtCore.QRect(10, 620, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.display_btn.setFont(font)
        self.display_btn.setObjectName("display_btn")
        self.get_coord_led_chb = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.get_coord_led_chb.setGeometry(QtCore.QRect(10, 90, 61, 25))
        self.get_coord_led_chb.setObjectName("get_coord_led_chb")
        self.current_scale_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.current_scale_lbl.setGeometry(QtCore.QRect(10, 130, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.current_scale_lbl.setFont(font)
        self.current_scale_lbl.setObjectName("current_scale_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pls_coordinates_lbl.setText(_translate("MainWindow", "Введите координаты"))
        self.display_btn.setText(_translate("MainWindow", "Отобразить карту"))
        self.get_coord_led_chb.setText(_translate("MainWindow", "Hide "))
        self.current_scale_lbl.setText(_translate("MainWindow", "Текущий маштаб карты: 14"))
